version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "No build step needed for static site"

artifacts:
  files:
    - '**/*'
  base-directory: '.'
